# Generated by Django 4.0 on 2022-08-23 08:35

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lodgings', '0001_initial'),
        ('users', '0003_user_security_token_expiration_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('lodging', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking', to='lodgings.lodging')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking', to='users.user')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
