# Generated by Django 4.0 on 2022-08-25 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('payment_pending', 'Payment pending'), ('paid', 'Paid'), ('canceled', 'Canceled')], default='payment_pending', max_length=50),
        ),
    ]
