# Generated by Django 4.0 on 2022-10-29 10:25

from django.db import migrations, models
import djlodging.domain.bookings.models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_booking_payment_intent_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='reference_code',
            field=models.CharField(default=djlodging.domain.bookings.models.generate_reference_code, max_length=6),
        ),
    ]
