# Generated by Django 4.0 on 2022-11-27 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_alter_booking_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='payment_expiration_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
