# Generated by Django 4.0 on 2022-08-24 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lodgings', '0002_lodging_number_of_people_lodging_number_of_rooms'),
    ]

    operations = [
        migrations.AddField(
            model_name='lodging',
            name='price',
            field=models.DecimalField(decimal_places=2, default=20, max_digits=7),
            preserve_default=False,
        ),
    ]
