# Generated by Django 4.0 on 2022-09-15 18:31

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('lodgings', '0003_lodging_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('score', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(10)])),
                ('lodging', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='lodgings.lodging')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
