# Generated by Django 4.0 on 2022-11-27 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lodgings', '0005_rename_type_lodging_kind'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lodging',
            options={'ordering': ('-created',)},
        ),
        migrations.AlterModelOptions(
            name='lodgingimage',
            options={'ordering': ('-created',)},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ('-created',)},
        ),
    ]
