version: '3.8'

services:
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ../src/djlodging/django_app/django_core/.env

  web:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    command: gunicorn djlodging.django_app.django_core.wsgi:application --bind 0.0.0.0:8000
    expose:
      - 8000
    env_file:
      - ../src/djlodging/django_app/django_core/.env
    depends_on:
      - db

  nginx:
    build: ./nginx
    ports:
      - 1337:80
    depends_on:
      - web

volumes:
  postgres_data:
    # services:
    #   db:
    #     image: postgres:12
    #     ports:
    #       - "5432:5432"
    #     environment:
    #       - POSTGRES_USER=postgres
    #       - POSTGRES_PASSWORD=postgres
    #       - POSTGRES_DB=postgres
