# Generated by Django 4.0 on 2022-08-15 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfirmationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=6)),
                ('sent_at', models.DateTimeField(auto_now=True)),
                ('sent_to', models.EmailField(max_length=100)),
            ],
        ),
    ]
