# Generated by Django 4.0 on 2022-08-17 10:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='registration_token',
            field=models.CharField(blank=True, default=uuid.uuid4, max_length=100),
        ),
    ]
