# Generated by Django 4.0 on 2022-08-22 12:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_registration_token_user_security_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='security_token_expiration_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 8, 22, 14, 25, 3, 124287, tzinfo=utc)),
        ),
    ]
