# Generated by Django 4.0 on 2022-08-23 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_registration_token_user_security_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='security_token_expiration_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
