# Generated by Django 4.0 on 2022-08-22 12:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_security_token_expiration_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='security_token_expiration_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 8, 22, 13, 27, 0, 380119, tzinfo=utc)),
        ),
    ]
