# Generated by Django 4.0 on 2022-08-25 17:27

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_security_token_expiration_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentProviderUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('customer_id', models.CharField(max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_user', to='users.user')),
            ],
            options={
                'verbose_name': 'Payment Provider User',
                'verbose_name_plural': 'Payment Provider Users',
            },
        ),
    ]
