# Generated by Django 4.0 on 2022-11-28 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_paymentprovideruser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='security_token_expiration_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
